Repository palantir/go-java-launcher, pull requests merged in 2022-04, with the labels that each got.

#152 Remove unused dep files
  Gopkg.lock
  Gopkg.toml
Labels: merge when ready, no changelog

#224 Update golang.org/x/crypto
  changelog/@unreleased/pr-224.v2.yml
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: merge when ready, autorelease

#228 Update golang.org/x/crypto
  changelog/@unreleased/pr-228.v2.yml
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: merge when ready, autorelease

#230 Revert "Excavator: Manage go module dependencies (#229)"
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: no changelog

#232 Update github.com/palantir/pkg/cli module to v1.0.2
  changelog/@unreleased/pr-232.v2.yml
  go.mod
  go.sum
  vendor/github.com/palantir/pkg/cli/godelw
  vendor/github.com/palantir/pkg/cli/main.go
  vendor/github.com/palantir/pkg/cli/on_exit.go
  vendor/golang.org/x/sys/unix/asm_linux_loong64.s
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/modules.txt
Labels: merge when ready, autorelease
